title: "Image Resizer"
url: "https://tools.itblognote.com"
baseurl: "/image-resizer"


email: thanhphatit95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Use these web tools to create and resize images.
github_username: thanhphatit